### ISSUE TITLE
reliese of v2.4.2 break SSR 

### ISSUE THREAD

**Issue by danielstaleiny** [ctrlplusb/react-sizeme#134]
v2.4.1 is working without problem with SSR. v2.4.2 throws error window is undefined with SSR. 

```
ReferenceError: window is not defined
    at module.exports (/home/anon/Github/nextjs/mobx/node_modules/element-resize-detector/src/reporter.js:21:18)
    at module.exports (/home/anon/Github/nextjs/mobx/node_modules/element-resize-detector/src/element-resize-detector.js:91:20)
    at createResizeDetector (/home/anon/Github/nextjs/mobx/node_modules/react-sizeme/src/resizeDetector.js:9:27)
    at resizeDetector (/home/anon/Github/nextjs/mobx/node_modules/react-sizeme/src/sizeMe.js:171:20)
    at Object.sizeMe (/home/anon/Github/nextjs/mobx/.next/dist/bundles/pages/webpack:/pages/index.js?f7ee:51:22)
    at __webpack_require__ (/home/anon/Github/nextjs/mobx/.next/dist/bundles/pages/webpack:/webpack/bootstrap 96d62891e60ba037ef65?3539:21:1)
    at Object.2 (/home/anon/Github/nextjs/mobx/.next/dist/bundles/pages/index.js:2885:18)
    at __webpack_require__ (/home/anon/Github/nextjs/mobx/.next/dist/bundles/pages/webpack:/webpack/bootstrap 96d62891e60ba037ef65?3539:21:1)
    at /home/anon/Github/nextjs/mobx/.next/dist/bundles/pages/webpack:/webpack/bootstrap 96d62891e60ba037ef65?3539:68:1
    at Object.<anonymous> (/home/anon/Github/nextjs/mobx/.next/dist/bundles/pages/index.js:73:10)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
```

errors is shown right after calling I wrap my component. first render goes with SSR. Previous version worked without problems.

**Comment by danielstaleiny** [comment]
apparently it trows in one of dependency 
https://github.com/wnr/element-resize-detector/blob/master/src/reporter.js

**Comment by ctrlplusb** [comment]
Thanks for the report

**Comment by ramonfritsch** [comment]
better set "2.4.1" on our `package.json` files for now

**Comment by danielstaleiny** [comment]
alright, this has to be resolved here and made sure downstream dependency is invoke only in browser context.
