### ISSUE TITLE
TS2349: Cannot invoke an expression whose type lacks a call signature. 

### ISSUE THREAD

**Issue by dongjiang1989** [ctrlplusb/react-sizeme#168]
const SizedReactLayoutGrid = sizeMe({ monitorWidth: true })(GridWrapper);

TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/data/dongjiang/.jenkins/workspace/grafana_master-ANMYDH2RGGFDAJ7NMI4J473MAL45SMZ2...' has no compatible call signatures.
    at emitError (/data/dongjiang/.jenkins/workspace/grafana_master-ANMYDH2RGGFDAJ7NMI4J473MAL45SMZ2QMSY2XNE2ND342EWDQFQ/src/code.huawei.com/cloudservice2/DevOps/grafana/node_modules/awesome-typescript-loader/src/instance.ts:462:30)
    at /data/dongjiang/.jenkins/workspace/grafana_master-ANMYDH2RGGFDAJ7NMI4J473MAL45SMZ2QMSY2XNE2ND342EWDQFQ/src/code.huawei.com/cloudservice2/DevOps/grafana/node_modules/awesome-typescript-loader/src/instance.ts:503:29
    at Array.forEach (<anonymous>)
    at /data/dongjiang/.jenkins/workspace/grafana_master-ANMYDH2RGGFDAJ7NMI4J473MAL45SMZ2QMSY2XNE2ND342EWDQFQ/src/code.huawei.com/cloudservice2/DevOps/grafana/node_modules/awesome-typescript-loader/src/instance.ts:503:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) ]

**Comment by ctrlplusb** [comment]
Can you show me how you are importing sizeMe?
